In [10]:
import numpy as np

# Replace 'your_file.npy' with the path to your .npy file
data = np.load('neighbor_distance_matrix.npy')

# Print or manipulate the data
print(data)


[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [11]:
data[0]

array([1.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [6]:
import numpy as np

# Replace 'your_file.npy' with the path to your .npy file
data = np.load('neighbor_index_matrix.npy')

# Print or manipulate the data
print(data)


[[  0 330 230 135 459 136]
 [  1 396 127 273 293 279]
 [  2 226 229 418  14  82]
 ...
 [487   8  67 126  59 142]
 [488 242 393 209 385 267]
 [489 296 183 157  28 474]]


In [7]:
data.shape

(490, 6)

In [8]:
data[330]

array([330,   0, 135, 136, 433, 230])

In [12]:
! pip install geopy

Defaulting to user installation because normal site-packages is not writeable
