In [1]:
import pandas as pd
import numpy as np


In [37]:
df = pd.read_csv('GA_features.csv')
df

Unnamed: 0.1  Unnamed: 0     county  tweets  contribution  n_poll  \
0               0           0    APPLING       0        235818       0   
1               1           1   ATKINSON       0         93026       0   
2               2           2      BACON       0        173074       0   
3               3           3      BAKER       0         72226       0   
4               4           4    BALDWIN       2        927608       0   
..            ...         ...        ...     ...           ...     ...   
154           154         154  WHITFIELD       0       4216384       1   
155           155         155     WILCOX       0        101176       0   
156           156         156     WILKES       0        142526       0   
157           157         157  WILKINSON       0         92444       0   
158           158         158      WORTH       0        230358       0   

     frac_unem  frac_votes  total_votes  registered_A_a  ...  frac_voted_A  \
0     0.160193    0.695728         8403             967  ...      0.155540   
1     0.117003    0.649241         3167             400  ...      0.187243   
2     0.115665    0.672325         4674             340  ...      0.085794   
3     0.179682    0.682852         1561             412  ...      0.383088   
4     0.173954    0.673200        18342            4601  ...      0.374932   
..         ...         ...          ...             ...  ...           ...   
154   0.070532    0.660559        36955            1040  ...      0.034745   
155   0.182849    0.690566         3294             570  ...      0.230419   
156   0.206583    0.703740         5024            1147  ...      0.344944   
157   0.163246    0.711561         4776            1151  ...      0.383585   
158   0.114777    0.645210         9322            1555  ...      0.212186   

     frac_voted_B  frac_voted_C  frac_voted_D  voted_E.1  frac_voted_F  \
0        0.783292      0.004165      0.012972   0.001071      0.004046   
1        0.729081      0.000947      0.050837   0.000947      0.003789   
2        0.858151      0.002353      0.010270   0.000642      0.003637   
3        0.570788      0.006406      0.006406   0.001281      0.002562   
4        0.572239      0.008123      0.007796   0.000872      0.005670   
..            ...           ...           ...        ...           ...   
154      0.749127      0.009552      0.127588   0.001380      0.009796   
155      0.740437      0.002429      0.007286   0.000607      0.003643   
156      0.605494      0.004976      0.004379   0.001393      0.005772   
157      0.581449      0.001675      0.002094   0.001466      0.003769   
158      0.746514      0.002145      0.004398   0.000536      0.005149   

     frac_voted_G  total_registers  latitude  longitude  
0        0.038915            12078   31.7492   -82.2889  
1        0.027155             4878   31.2971   -82.8800  
2        0.039153             6952   31.5537   -82.4527  
3        0.029468             2286   31.3262   -84.4447  
4        0.030367            27246   33.0693   -83.2496  
..            ...              ...       ...        ...  
154      0.067812            55945   34.8056   -84.9672  
155      0.015179             4770   31.9729   -83.4323  
156      0.033041             7139   33.7819   -82.7432  
157      0.025963             6712   32.8024   -83.1712  
158      0.029071            14448   31.5515   -83.8509  

[159 rows x 124 columns]

In [21]:
# Calculate the mean of the 'n_poll' column
mean_value = df['n_poll'].mean()

# Update the column based on the condition
df['n_poll'] = df['n_poll'].apply(lambda x: 0 if x < mean_value else 1)

# View the updated DataFrame
df

Unnamed: 0     county  tweets  contribution  n_poll   fr_unem  fr_votes  \
0             0    APPLING       0        235818       0  0.160193  0.695728   
1             1   ATKINSON       0         93026       0  0.117003  0.649241   
2             2      BACON       0        173074       0  0.115665  0.672325   
3             3      BAKER       0         72226       0  0.179682  0.682852   
4             4    BALDWIN       2        927608       0  0.173954  0.673200   
..          ...        ...     ...           ...     ...       ...       ...   
154         154  WHITFIELD       0       4216384       1  0.070532  0.660559   
155         155     WILCOX       0        101176       0  0.182849  0.690566   
156         156     WILKES       0        142526       0  0.206583  0.703740   
157         157  WILKINSON       0         92444       0  0.163246  0.711561   
158         158      WORTH       0        230358       0  0.114777  0.645210   

     total_votes  registered_A_a  registered_A_b  ...  voted_A.1  voted_B.1  \
0           8403             967            1195  ...   0.155540   0.783292   
1           3167             400             512  ...   0.187243   0.729081   
2           4674             340             559  ...   0.085794   0.858151   
3           1561             412             517  ...   0.383088   0.570788   
4          18342            4601            6382  ...   0.374932   0.572239   
..           ...             ...             ...  ...        ...        ...   
154        36955            1040            1159  ...   0.034745   0.749127   
155         3294             570             748  ...   0.230419   0.740437   
156         5024            1147            1529  ...   0.344944   0.605494   
157         4776            1151            1456  ...   0.383585   0.581449   
158         9322            1555            2004  ...   0.212186   0.746514   

     voted_C.1  voted_D.1  voted_E.1  voted_F.1  voted_G.1  total_registers  \
0     0.004165   0.012972   0.001071   0.004046   0.038915            12078   
1     0.000947   0.050837   0.000947   0.003789   0.027155             4878   
2     0.002353   0.010270   0.000642   0.003637   0.039153             6952   
3     0.006406   0.006406   0.001281   0.002562   0.029468             2286   
4     0.008123   0.007796   0.000872   0.005670   0.030367            27246   
..         ...        ...        ...        ...        ...              ...   
154   0.009552   0.127588   0.001380   0.009796   0.067812            55945   
155   0.002429   0.007286   0.000607   0.003643   0.015179             4770   
156   0.004976   0.004379   0.001393   0.005772   0.033041             7139   
157   0.001675   0.002094   0.001466   0.003769   0.025963             6712   
158   0.002145   0.004398   0.000536   0.005149   0.029071            14448   

     latitude  longitude  
0     31.7492   -82.2889  
1     31.2971   -82.8800  
2     31.5537   -82.4527  
3     31.3262   -84.4447  
4     33.0693   -83.2496  
..        ...        ...  
154   34.8056   -84.9672  
155   31.9729   -83.4323  
156   33.7819   -82.7432  
157   32.8024   -83.1712  
158   31.5515   -83.8509  

[159 rows x 123 columns]

In [24]:
df.columns

Index(['Unnamed: 0', 'county', 'tweets', 'contribution', 'n_poll', 'fr_unem',
       'fr_votes', 'total_votes', 'registered_A_a', 'registered_A_b',
       ...
       'voted_A.1', 'voted_B.1', 'voted_C.1', 'voted_D.1', 'voted_E.1',
       'voted_F.1', 'voted_G.1', 'total_registers', 'latitude', 'longitude'],
      dtype='object', length=123)

In [38]:
# Identify columns where all values are between 0 and 1, exclude 'county', and check if not already prefixed with 'frac_'
columns_to_rename = [
    col for col in df.columns 
    if col != 'county' and not col.startswith('frac_') 
    and (df[col].astype(float) >= 0).all() 
    and (df[col].astype(float) < 1).all()
]

# Rename the columns
df.rename(columns={col: f'frac_{col}' for col in columns_to_rename}, inplace=True)

# View the updated DataFrame
print(df)


     Unnamed: 0.1  Unnamed: 0     county  tweets  contribution  n_poll  \
0               0           0    APPLING       0        235818       0   
1               1           1   ATKINSON       0         93026       0   
2               2           2      BACON       0        173074       0   
3               3           3      BAKER       0         72226       0   
4               4           4    BALDWIN       2        927608       0   
..            ...         ...        ...     ...           ...     ...   
154           154         154  WHITFIELD       0       4216384       1   
155           155         155     WILCOX       0        101176       0   
156           156         156     WILKES       0        142526       0   
157           157         157  WILKINSON       0         92444       0   
158           158         158      WORTH       0        230358       0   

     frac_unem  frac_votes  total_votes  registered_A_a  ...  frac_voted_A  \
0     0.160193    0.695728       

In [41]:
# Remove '.1' from all column names
df.columns = df.columns.str.replace('.1', '', regex=False)

df

Unnamed: 0  Unnamed: 0     county  tweets  contribution  n_poll  \
0             0           0    APPLING       0        235818       0   
1             1           1   ATKINSON       0         93026       0   
2             2           2      BACON       0        173074       0   
3             3           3      BAKER       0         72226       0   
4             4           4    BALDWIN       2        927608       0   
..          ...         ...        ...     ...           ...     ...   
154         154         154  WHITFIELD       0       4216384       1   
155         155         155     WILCOX       0        101176       0   
156         156         156     WILKES       0        142526       0   
157         157         157  WILKINSON       0         92444       0   
158         158         158      WORTH       0        230358       0   

     frac_unem  frac_votes  total_votes  registered_A_a  ...  frac_voted_A  \
0     0.160193    0.695728         8403             967  ...      0.155540   
1     0.117003    0.649241         3167             400  ...      0.187243   
2     0.115665    0.672325         4674             340  ...      0.085794   
3     0.179682    0.682852         1561             412  ...      0.383088   
4     0.173954    0.673200        18342            4601  ...      0.374932   
..         ...         ...          ...             ...  ...           ...   
154   0.070532    0.660559        36955            1040  ...      0.034745   
155   0.182849    0.690566         3294             570  ...      0.230419   
156   0.206583    0.703740         5024            1147  ...      0.344944   
157   0.163246    0.711561         4776            1151  ...      0.383585   
158   0.114777    0.645210         9322            1555  ...      0.212186   

     frac_voted_B  frac_voted_C  frac_voted_D  frac_voted_E  frac_voted_F  \
0        0.783292      0.004165      0.012972      0.001071      0.004046   
1        0.729081      0.000947      0.050837      0.000947      0.003789   
2        0.858151      0.002353      0.010270      0.000642      0.003637   
3        0.570788      0.006406      0.006406      0.001281      0.002562   
4        0.572239      0.008123      0.007796      0.000872      0.005670   
..            ...           ...           ...           ...           ...   
154      0.749127      0.009552      0.127588      0.001380      0.009796   
155      0.740437      0.002429      0.007286      0.000607      0.003643   
156      0.605494      0.004976      0.004379      0.001393      0.005772   
157      0.581449      0.001675      0.002094      0.001466      0.003769   
158      0.746514      0.002145      0.004398      0.000536      0.005149   

     frac_voted_G  total_registers  latitude  longitude  
0        0.038915            12078   31.7492   -82.2889  
1        0.027155             4878   31.2971   -82.8800  
2        0.039153             6952   31.5537   -82.4527  
3        0.029468             2286   31.3262   -84.4447  
4        0.030367            27246   33.0693   -83.2496  
..            ...              ...       ...        ...  
154      0.067812            55945   34.8056   -84.9672  
155      0.015179             4770   31.9729   -83.4323  
156      0.033041             7139   33.7819   -82.7432  
157      0.025963             6712   32.8024   -83.1712  
158      0.029071            14448   31.5515   -83.8509  

[159 rows x 124 columns]

In [42]:
df.to_csv('GA_features.csv')

In [43]:
df

Unnamed: 0  Unnamed: 0     county  tweets  contribution  n_poll  \
0             0           0    APPLING       0        235818       0   
1             1           1   ATKINSON       0         93026       0   
2             2           2      BACON       0        173074       0   
3             3           3      BAKER       0         72226       0   
4             4           4    BALDWIN       2        927608       0   
..          ...         ...        ...     ...           ...     ...   
154         154         154  WHITFIELD       0       4216384       1   
155         155         155     WILCOX       0        101176       0   
156         156         156     WILKES       0        142526       0   
157         157         157  WILKINSON       0         92444       0   
158         158         158      WORTH       0        230358       0   

     frac_unem  frac_votes  total_votes  registered_A_a  ...  frac_voted_A  \
0     0.160193    0.695728         8403             967  ...      0.155540   
1     0.117003    0.649241         3167             400  ...      0.187243   
2     0.115665    0.672325         4674             340  ...      0.085794   
3     0.179682    0.682852         1561             412  ...      0.383088   
4     0.173954    0.673200        18342            4601  ...      0.374932   
..         ...         ...          ...             ...  ...           ...   
154   0.070532    0.660559        36955            1040  ...      0.034745   
155   0.182849    0.690566         3294             570  ...      0.230419   
156   0.206583    0.703740         5024            1147  ...      0.344944   
157   0.163246    0.711561         4776            1151  ...      0.383585   
158   0.114777    0.645210         9322            1555  ...      0.212186   

     frac_voted_B  frac_voted_C  frac_voted_D  frac_voted_E  frac_voted_F  \
0        0.783292      0.004165      0.012972      0.001071      0.004046   
1        0.729081      0.000947      0.050837      0.000947      0.003789   
2        0.858151      0.002353      0.010270      0.000642      0.003637   
3        0.570788      0.006406      0.006406      0.001281      0.002562   
4        0.572239      0.008123      0.007796      0.000872      0.005670   
..            ...           ...           ...           ...           ...   
154      0.749127      0.009552      0.127588      0.001380      0.009796   
155      0.740437      0.002429      0.007286      0.000607      0.003643   
156      0.605494      0.004976      0.004379      0.001393      0.005772   
157      0.581449      0.001675      0.002094      0.001466      0.003769   
158      0.746514      0.002145      0.004398      0.000536      0.005149   

     frac_voted_G  total_registers  latitude  longitude  
0        0.038915            12078   31.7492   -82.2889  
1        0.027155             4878   31.2971   -82.8800  
2        0.039153             6952   31.5537   -82.4527  
3        0.029468             2286   31.3262   -84.4447  
4        0.030367            27246   33.0693   -83.2496  
..            ...              ...       ...        ...  
154      0.067812            55945   34.8056   -84.9672  
155      0.015179             4770   31.9729   -83.4323  
156      0.033041             7139   33.7819   -82.7432  
157      0.025963             6712   32.8024   -83.1712  
158      0.029071            14448   31.5515   -83.8509  

[159 rows x 124 columns]

In [4]:
df = df[['latitude','longitude']]
df

latitude  longitude
0     31.7492   -82.2889
1     31.2971   -82.8800
2     31.5537   -82.4527
3     31.3262   -84.4447
4     33.0693   -83.2496
..        ...        ...
154   34.8056   -84.9672
155   31.9729   -83.4323
156   33.7819   -82.7432
157   32.8024   -83.1712
158   31.5515   -83.8509

[159 rows x 2 columns]

In [5]:

# Haversine formula to calculate the distance
def haversine(lat1, lon1, lat2, lon2):
    # Radius of Earth in kilometers
    R = 6371.0
    # Convert degrees to radians
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])
    # Haversine formula
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = np.sin(dlat / 2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon / 2)**2
    c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1 - a))
    return c

# Create an empty DataFrame for the distance matrix
distance_matrix = pd.DataFrame(index=df.index, columns=df.index)

# Calculate the distance between each pair of coordinates
for i, county1 in df.iterrows():
    for j, county2 in df.iterrows():
        lat1, lon1 = county1['latitude'], county1['longitude']
        lat2, lon2 = county2['latitude'], county2['longitude']
        distance_matrix.loc[i, j] = haversine(lat1, lon1, lat2, lon2)

# Convert the matrix to float
distance_matrix = distance_matrix.astype(float)

# View the distance matrix
print(distance_matrix)

          0         1         2         3         4         5         6    \
0    0.000000  0.011815  0.004191  0.032907  0.027041  0.048781  0.044378   
1    0.011815  0.000000  0.007782  0.023337  0.031409  0.054120  0.048620   
2    0.004191  0.007782  0.000000  0.029927  0.028946  0.051216  0.046418   
3    0.032907  0.023337  0.029927  0.000000  0.035172  0.054645  0.047774   
4    0.027041  0.031409  0.028946  0.035172  0.000000  0.022714  0.017476   
..        ...       ...       ...       ...       ...       ...       ...   
154  0.066121  0.068420  0.067599  0.061206  0.039202  0.022544  0.022965   
155  0.017393  0.014369  0.016274  0.018805  0.019324  0.041574  0.035499   
156  0.036098  0.043415  0.039123  0.049632  0.014460  0.014786  0.014523   
157  0.022525  0.026623  0.024241  0.031915  0.004798  0.027497  0.022231   
158  0.023462  0.015126  0.020795  0.009677  0.027936  0.049191  0.042664   

          7         8         9    ...       149       150       151  \
0  

In [8]:
R = 6371.0
distance_matrix = distance_matrix*R
distance_matrix

0           1           2           3           4           5    \
0      0.000000   75.274674   26.701265  209.647500  172.277441  310.786106   
1     75.274674    0.000000   49.577632  148.680055  200.105342  344.799725   
2     26.701265   49.577632    0.000000  190.664001  184.415714  326.299217   
3    209.647500  148.680055  190.664001    0.000000  224.078145  348.144738   
4    172.277441  200.105342  184.415714  224.078145    0.000000  144.709071   
..          ...         ...         ...         ...         ...         ...   
154  421.254913  435.905220  430.670229  389.941235  249.754703  143.629224   
155  110.811403   91.546435  103.680867  119.809547  123.111576  264.868476   
156  229.981969  276.594476  249.251846  316.203556   92.125494   94.204379   
157  143.509073  169.616528  154.438833  203.330274   30.566507  175.185830   
158  149.477343   96.369584  132.487001   61.653679  177.979551  313.398831   

            6           7           8           9    ...         149  \
0    282.731206  364.924267   88.090637  103.540521  ...  143.804276   
1    309.760617  374.829216   60.733907   33.303489  ...  186.130902   
2    295.727474  372.486090   76.199880   79.929541  ...  160.702865   
3    304.367866  325.849603  125.630921  115.581388  ...  239.751518   
4    111.339664  196.360847  145.635374  199.414745  ...   43.732271   
..          ...         ...         ...         ...  ...         ...   
154  146.313020   64.207209  375.566748  424.557719  ...  286.084075   
155  226.164086  283.931727   31.008750   79.832961  ...  125.874562   
156   92.523758  199.836899  229.232044  282.348676  ...   90.467201   
157  141.631304  222.288630  116.024427  169.817166  ...   39.665202   
158  271.811837  312.647616   64.005706   66.442651  ...  186.281924   

            150         151         152         153         154         155  \
0     41.518975  216.103631   58.000109  349.546834  421.254913  110.811403   
1     95.671396  178.766689   92.357261  381.102525  435.905220   91.546435   
2     50.780216  205.742403   67.708337  364.406107  430.670229  103.680867   
3    241.124284   80.757035  184.937582  374.875474  389.941235  119.809547   
4    210.167077  166.746136  116.745266  181.281815  249.754703  123.111576   
..          ...         ...         ...         ...         ...         ...   
154  459.854939  309.184362  364.181717  112.900025    0.000000  345.703606   
155  150.744715  105.809070   68.602372  298.714901  345.703606    0.000000   
156  259.790027  256.316726  185.125448  133.271672  233.868460  211.192660   
157  182.438251  154.379228   86.962025  211.846529  277.751815   95.438783   
158  183.267131   86.092490  123.596345  344.272911  376.449529   61.333743   

            156         157         158  
0    229.981969  143.509073  149.477343  
1    276.594476  169.616528   96.369584  
2    249.251846  154.438833  132.487001  
3    316.203556  203.330274   61.653679  
4     92.125494   30.566507  177.979551  
..          ...         ...         ...  
154  233.868460  277.751815  376.449529  
155  211.192660   95.438783   61.333743  
156    0.000000  115.952560  268.805933  
157  115.952560    0.000000  153.097877  
158  268.805933  153.097877    0.000000  

[159 rows x 159 columns]

In [9]:
# Optionally save to a CSV file
distance_matrix.to_csv("distance_matrix.csv")


In [10]:
# Function to keep only the top 5 closest neighbors and apply inverse transformation
def transform_distance_matrix(matrix):
    # Create a new matrix to store the transformed values
    transformed_matrix = matrix.copy()
    
    for i in matrix.index:
        # Sort the distances for the current row
        sorted_indices = matrix.loc[i].sort_values().index[:5]  # Get top 5 indices
        for j in matrix.columns:
            if j in sorted_indices:
                # Inverse transformation (set 1 / distance)
                transformed_matrix.loc[i, j] = 1 / matrix.loc[i, j] if matrix.loc[i, j] != 0 else 1
            else:
                # Set all other distances to 0
                transformed_matrix.loc[i, j] = 0
    
    return transformed_matrix

# Transform the distance matrix
transformed_matrix = transform_distance_matrix(distance_matrix)

transformed_matrix

0    1         2    3         4    5    6    7         8    \
0    1.000000  0.0  0.037451  0.0  0.000000  0.0  0.0  0.0  0.000000   
1    0.000000  1.0  0.000000  0.0  0.000000  0.0  0.0  0.0  0.000000   
2    0.037451  0.0  1.000000  0.0  0.000000  0.0  0.0  0.0  0.000000   
3    0.000000  0.0  0.000000  1.0  0.000000  0.0  0.0  0.0  0.000000   
4    0.000000  0.0  0.000000  0.0  1.000000  0.0  0.0  0.0  0.000000   
..        ...  ...       ...  ...       ...  ...  ...  ...       ...   
154  0.000000  0.0  0.000000  0.0  0.000000  0.0  0.0  0.0  0.000000   
155  0.000000  0.0  0.000000  0.0  0.000000  0.0  0.0  0.0  0.032249   
156  0.000000  0.0  0.000000  0.0  0.000000  0.0  0.0  0.0  0.000000   
157  0.000000  0.0  0.000000  0.0  0.032716  0.0  0.0  0.0  0.000000   
158  0.000000  0.0  0.000000  0.0  0.000000  0.0  0.0  0.0  0.000000   

          9    ...       149       150  151  152  153  154  155  156  \
0    0.000000  ...  0.000000  0.024085  0.0  0.0  0.0  0.0  0.0  0.0   
1    0.030027  ...  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0  0.0   
2    0.000000  ...  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0  0.0   
3    0.000000  ...  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0  0.0   
4    0.000000  ...  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0  0.0   
..        ...  ...       ...       ...  ...  ...  ...  ...  ...  ...   
154  0.000000  ...  0.000000  0.000000  0.0  0.0  0.0  1.0  0.0  0.0   
155  0.000000  ...  0.000000  0.000000  0.0  0.0  0.0  0.0  1.0  0.0   
156  0.000000  ...  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0  1.0   
157  0.000000  ...  0.025211  0.000000  0.0  0.0  0.0  0.0  0.0  0.0   
158  0.000000  ...  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0  0.0   

          157  158  
0    0.000000  0.0  
1    0.000000  0.0  
2    0.000000  0.0  
3    0.000000  0.0  
4    0.032716  0.0  
..        ...  ...  
154  0.000000  0.0  
155  0.000000  0.0  
156  0.000000  0.0  
157  1.000000  0.0  
158  0.000000  1.0  

[159 rows x 159 columns]

In [15]:
transformed_matrix.iloc[:,150]

0      0.024085
1      0.000000
2      0.000000
3      0.000000
4      0.000000
         ...   
154    0.000000
155    0.000000
156    0.000000
157    0.000000
158    0.000000
Name: 150, Length: 159, dtype: float64

In [16]:
matrix_array = transformed_matrix.to_numpy()

# Save as a .npy file
np.save("distance_matrix.npy", matrix_array)

# To load the .npy file later
loaded_matrix = np.load("distance_matrix.npy")

# Optional: Convert back to DataFrame if needed
loaded_df = pd.DataFrame(loaded_matrix, index=transformed_matrix.index, columns=transformed_matrix.columns)
loaded_df

0    1         2    3         4    5    6    7         8    \
0    1.000000  0.0  0.037451  0.0  0.000000  0.0  0.0  0.0  0.000000   
1    0.000000  1.0  0.000000  0.0  0.000000  0.0  0.0  0.0  0.000000   
2    0.037451  0.0  1.000000  0.0  0.000000  0.0  0.0  0.0  0.000000   
3    0.000000  0.0  0.000000  1.0  0.000000  0.0  0.0  0.0  0.000000   
4    0.000000  0.0  0.000000  0.0  1.000000  0.0  0.0  0.0  0.000000   
..        ...  ...       ...  ...       ...  ...  ...  ...       ...   
154  0.000000  0.0  0.000000  0.0  0.000000  0.0  0.0  0.0  0.000000   
155  0.000000  0.0  0.000000  0.0  0.000000  0.0  0.0  0.0  0.032249   
156  0.000000  0.0  0.000000  0.0  0.000000  0.0  0.0  0.0  0.000000   
157  0.000000  0.0  0.000000  0.0  0.032716  0.0  0.0  0.0  0.000000   
158  0.000000  0.0  0.000000  0.0  0.000000  0.0  0.0  0.0  0.000000   

          9    ...       149       150  151  152  153  154  155  156  \
0    0.000000  ...  0.000000  0.024085  0.0  0.0  0.0  0.0  0.0  0.0   
1    0.030027  ...  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0  0.0   
2    0.000000  ...  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0  0.0   
3    0.000000  ...  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0  0.0   
4    0.000000  ...  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0  0.0   
..        ...  ...       ...       ...  ...  ...  ...  ...  ...  ...   
154  0.000000  ...  0.000000  0.000000  0.0  0.0  0.0  1.0  0.0  0.0   
155  0.000000  ...  0.000000  0.000000  0.0  0.0  0.0  0.0  1.0  0.0   
156  0.000000  ...  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0  1.0   
157  0.000000  ...  0.025211  0.000000  0.0  0.0  0.0  0.0  0.0  0.0   
158  0.000000  ...  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0  0.0   

          157  158  
0    0.000000  0.0  
1    0.000000  0.0  
2    0.000000  0.0  
3    0.000000  0.0  
4    0.032716  0.0  
..        ...  ...  
154  0.000000  0.0  
155  0.000000  0.0  
156  0.000000  0.0  
157  1.000000  0.0  
158  0.000000  1.0  

[159 rows x 159 columns]

In [17]:
# Function to get the indices of the top 5 closest neighbors
def get_closest_neighbors_indices(matrix, top_n=5):
    closest_indices = []
    for i in matrix.index:
        # Sort distances for each row and get the indices of the smallest values
        closest = matrix.loc[i].nsmallest(top_n + 1).index.tolist()  # +1 to include self
        closest_indices.append(closest)
    return np.array(closest_indices)

# Extract the closest neighbors' indices
closest_neighbors_indices = get_closest_neighbors_indices(distance_matrix)

# Save as .npy file
np.save("index_matrix.npy", closest_neighbors_indices)

# View the result
print(closest_neighbors_indices)

# To load the file later
loaded_indices = np.load("index_matrix.npy")
loaded_indices

[[  0   2  79 131 150 137]
 [  1  33   9  85  31   2]
 [  2   0 112  79  33   1]
 [  3 100  18  46  99  48]
 [  4  83 116 157  69 149]
 [  5  58  77 126  68  67]
 [  6  77 146  66 107  28]
 [  7  63  27  56 109  32]
 [  8  76 155 133 141  33]
 [  9  36  85   1 136  76]
 [ 10  83  38 110 142 101]
 [ 11 115 142  75  44  86]
 [ 12 112 150  19  62 147]
 [ 13  91 135  36  34  85]
 [ 14  88  24  50  90  53]
 [ 15  53  20  50 123  81]
 [ 16  81 120  80 123  35]
 [ 17  78  74  84 125 101]
 [ 18   3 119 134  48  29]
 [ 19  62  12  23  97 112]
 [ 20  52  15  53 137 131]
 [ 21  70  47  73  37 109]
 [ 22 154 145  40 104  63]
 [ 23 147  19  12  31 112]
 [ 24  14  88  50  97  90]
 [ 25 105  95 127 151  71]
 [ 26  56 145  63  40 154]
 [ 27 111  57   7  32  41]
 [ 28 107  94  77 108   6]
 [ 29 119 117  48  18 127]
 [ 30  55  74  42  59 125]
 [ 31  49 147  85   1  91]
 [ 32  59 109  47  27  42]
 [ 33   1  79   2  76   8]
 [ 34  36 136 135 100 158]
 [ 35  96 120  89 148  61]
 [ 36   9  34 136  85  13]
 

array([[  0,   2,  79, 131, 150, 137],
       [  1,  33,   9,  85,  31,   2],
       [  2,   0, 112,  79,  33,   1],
       [  3, 100,  18,  46,  99,  48],
       [  4,  83, 116, 157,  69, 149],
       [  5,  58,  77, 126,  68,  67],
       [  6,  77, 146,  66, 107,  28],
       [  7,  63,  27,  56, 109,  32],
       [  8,  76, 155, 133, 141,  33],
       [  9,  36,  85,   1, 136,  76],
       [ 10,  83,  38, 110, 142, 101],
       [ 11, 115, 142,  75,  44,  86],
       [ 12, 112, 150,  19,  62, 147],
       [ 13,  91, 135,  36,  34,  85],
       [ 14,  88,  24,  50,  90,  53],
       [ 15,  53,  20,  50, 123,  81],
       [ 16,  81, 120,  80, 123,  35],
       [ 17,  78,  74,  84, 125, 101],
       [ 18,   3, 119, 134,  48,  29],
       [ 19,  62,  12,  23,  97, 112],
       [ 20,  52,  15,  53, 137, 131],
       [ 21,  70,  47,  73,  37, 109],
       [ 22, 154, 145,  40, 104,  63],
       [ 23, 147,  19,  12,  31, 112],
       [ 24,  14,  88,  50,  97,  90],
       [ 25, 105,  95, 12

In [18]:
loaded_indices.shape

(159, 6)